### ISSUE TITLE
2.2 Works, 2.2.5 does not.

### ISSUE THREAD

**Issue by Zilacon** [cyberpwnn/React#29]
Hello, I was using 2.2 just fine and decided to update to 2.2.5 but it does not seem to like 1.7.10.

Here are some pics of the error.
![screenshot_59](https://cloud.githubusercontent.com/assets/3002248/15983763/1eb54e5a-2f67-11e6-8494-90bbb422d72d.png)
![screenshot_60](https://cloud.githubusercontent.com/assets/3002248/15983764/1eb8a834-2f67-11e6-954c-dd3c230cf309.png)

**Comment by cyberpwnn** [comment]
Does it still fail?

**Comment by cyberpwnn** [comment]
I fixed the issue with chatcolor on 2.2.8 or so. Does it still fail for you?

**Comment by Zilacon** [comment]
I have yet to try, ill do that now.

**Comment by cyberpwnn** [comment]
Make sure your on the latest version

**Comment by Zilacon** [comment]
Just grabbed 2.3.4

**Comment by Zilacon** [comment]
Nope same problem.

````
[19:43:15 INFO]: [React] Enabling React v2.3.4p
[19:43:16 ERROR]: Error occurred while enabling React v2.3.4p (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
	at org.cyberpwn.react.timings.PaperTimings.<clinit>(PaperTimings.java:34) ~[?:?]
	at org.cyberpwn.react.controller.TimingsController.<init>(TimingsController.java:46) ~[?:?]
	at org.cyberpwn.react.React.doEnable(React.java:174) ~[?:?]
	at org.cyberpwn.react.React.onEnable(React.java:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:639) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
````

**Comment by cyberpwnn** [comment]
Paper timings it is

**Comment by cyberpwnn** [comment]
2.3.5 will fix it.

**Comment by Zilacon** [comment]
Ok. Let me know when its out.

**Comment by cyberpwnn** [comment]
PaperTimings actually might not work for 1.7. There is no bukkit alternative for other things such as basecomponents. Ill find a way i can fix this hopefully

**Comment by Zilacon** [comment]
Well my server is using Spigot, Bukkit, Cauldron, Thermos, Forge, and probably 10 more APIs...

**Comment by cyberpwnn** [comment]
it cant find md5's apis which are needed

However i can usually just revert to the bukkit "chatcolor"

In this case it uses more of it. I have attempted to remove them and use another method of getting timings. I am testing it now

**Comment by cyberpwnn** [comment]
Try 2.3.5

**Comment by Zilacon** [comment]
Seems to be working now.
````
[20:15:41 INFO]: [React] Enabling React v2.3.5p
[20:15:42 ERROR]: [React] Plugin React v2.3.5p has failed to register events for class org.cyberpwn.react.src.posuere because org/bukkit/event/entity/EntitySpawnEvent does not exist.
[20:15:42 INFO]: __________  ___________    _____    _________   ___________
[20:15:42 INFO]: \______   \ \_   _____/   /  _  \   \_   ___ \  \__    ___/
[20:15:42 INFO]:  |       _/  |    __)_   /  /_\  \  /    \  \/    |    |   
[20:15:42 INFO]:  |    |   \  |        \ /    |    \ \     \____   |    |   
[20:15:42 INFO]:  |____|_  / /_______  / \____|__  /  \______  /   |____|   
[20:15:42 INFO]:         \/          \/          \/          \/             
[20:15:42 INFO]: React v2.3.5p(2305) 13 Controllers, 24 Samplers, 13 Actions
````

**Comment by Zilacon** [comment]
Thanks

**Comment by cyberpwnn** [comment]
No problem
