### ISSUE TITLE
Could not pass event PlayerDeathEvent

### ISSUE THREAD

**Issue by NelsonHD** [cyberpwnn/React#33]
```
[21:11:22] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to React v2.8.9p
org.bukkit.event.EventException
    at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:77) ~[?:?]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityLiving.O(EntityLiving.java:1183) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.Entity.K(Entity.java:327) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:169) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:247) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1448) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:173) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:285) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:382) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_91]
    at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_91]
    at org.cyberpwn.react.controller.LimitingController.act(LimitingController.java:204) ~[?:?]
    at org.cyberpwn.react.controller.LimitingController.on(LimitingController.java:166) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor781.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:67) ~[?:?]
    ... 27 more
```

**Comment by cyberpwnn** [comment]
This will be fixed 

Looks like a custom entity.

You also might want to try turning off LimitingController as a temp fix, but that error wont cause issues.
