### ISSUE TITLE
Timings doesn't work?

### ISSUE THREAD

**Issue by RoxydMineBone** [cyberpwnn/React#39]
# /react timings and /react plugins doesn't work.
## **MSG CHAT:**
**/react plugins**
  "Nothing"

**/react timings**
  "Data has not been prepared yet. Please wait up to 5 minutes." 
The 5 minutes spent half an hour ago.

Error console:  *It is always repeated*
`[11:54:34] [Thread-39/WARN]: Exception in thread "Thread-39" 
[11:54:34] [Thread-39/WARN]: java.lang.NoSuchMethodError: org.spigotmc.CustomTimingsHandler.printTimings(Ljava/io/PrintStream;)V
[11:54:34] [Thread-39/WARN]: 	at org.cyberpwn.react.timings.TimingsProcessor.poll(TimingsProcessor.java:55)
[11:54:34] [Thread-39/WARN]: 	at org.cyberpwn.react.timings.TimingsProcessor.run(TimingsProcessor.java:44)`

**Comment by SwiftSwamp** [comment]
Recently Spigot has changed the servers for where the timings are stored, make sure to update to the latest jars to ensure the timings are getting sent to the proper servers, otherwise you'll receive these errors.
