### ISSUE TITLE
Some Errors on 1.7.10

### ISSUE THREAD

**Issue by Xuwznln** [cyberpwnn/React#4]
Some errors
`[11:14:19] [Server thread/INFO]: OVERBOSE: /Internal: Loaded Configuration for action-collect-garbage
[11:14:19] [Server thread/ERROR]: Error occurred while enabling React v1.5.8p (Is it up to date?)
java.lang.NoSuchFieldError: MUTTON
	at com.glacialrush.react.actions.ActionCullDrops.onNewConfig(ActionCullDrops.java:182) ~[?:?]
	at com.glacialrush.react.controllers.DataController.load(DataController.java:136) ~[?:?]
	at com.glacialrush.react.controllers.ActionController.load(ActionController.java:57) ~[?:?]
	at com.glacialrush.react.controllers.ActionController.start(ActionController.java:65) ~[?:?]
	at com.glacialrush.react.React.onEnable(React.java:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.55]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:513) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:487) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:447) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]`

`[11:16:05] [Server thread/INFO]: Xu_wznln issued server command: /react status
[11:16:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'react' in plugin React v1.5.8p
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.55]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1614.55]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1366) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1103) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at com.glacialrush.react.actions.ActionInstabilityCause.pollHeaftSamples(ActionInstabilityCause.java:365) ~[?:?]
	at com.glacialrush.react.actions.ActionInstabilityCause.pagePollSamples(ActionInstabilityCause.java:407) ~[?:?]
	at com.glacialrush.react.actions.ActionInstabilityCause.query(ActionInstabilityCause.java:470) ~[?:?]
	at com.glacialrush.react.controllers.CommandController.onCommand(CommandController.java:221) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.55]
	... 13 more`

**Comment by cyberpwnn** [comment]
Try updating to 1.6.4 or later.

**Comment by Xuwznln** [comment]
It's all right now except for map. Much thanks and keep on working.
Can you add the console message to the remote client? Add more messages when React is working. Just like React is collecting garbage and show a message to players and log the action to show in the React client. It will be much better.

**Comment by cyberpwnn** [comment]
Yeah, i can add an overbose option for the console
