### ISSUE TITLE
BlockBreakEvent

### ISSUE THREAD

**Issue by Metisuneatn** [cyberpwnn/React#42]
`[11:35:51] [Server thread/ERROR]: Could not pass event BlockBreakEvent to React v3.1p
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:835) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: ORB_PICKUP
	at org.cyberpwn.react.action.ActionTeleportDrops.onBreak(ActionTeleportDrops.java:60) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_latest.jar:git-Spigot-f950f8e-c4baa9c]
	... 17 more`

During the time of this console spam there is dramatic tps drop from chunk rendering. In the time frame when a player is mining or breaking anything it will either delete or go to their inventory instantly. At this time silk touch does not work, breaking stone goes to cobble, and shears/crops/other things just delete and vanish. 

This was also tested on a server with essentials and vault and we were able to recreate the issue showing no plugins are clashing with this as told prior.

**Comment by cyberpwnn** [comment]
Turn off the action for auto drop
