### ISSUE TITLE
Many problems with react

### ISSUE THREAD

**Issue by dimon7147** [cyberpwnn/React#53]
Server work on Thermos 1.7.10
**1. When plugin start in console**:`Error occurred while enabling React v4.2.3p (Is it up to date?)
java.lang.NoSuchFieldError: ARMOR_STAND
	at org.cyberpwn.react.action.ActionCullEntities.onNewConfig(ActionCullEntities.java:291) ~[?:?]
	at org.cyberpwn.react.controller.DataController.load(DataController.java:138) ~[?:?]
	at org.cyberpwn.react.controller.ActionController.load(ActionController.java:66) ~[?:?]
	at org.cyberpwn.react.controller.ActionController.start(ActionController.java:75) ~[?:?]
	at org.cyberpwn.react.React.doEnable(React.java:226) ~[?:?]
	at org.cyberpwn.react.React.onEnable(React.java:127) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**and**:`
Task #99381 for React v4.2.6p generated an exception
java.lang.NullPointerException
	at org.cyberpwn.react.sampler.SampleMemoryUsed.formatted(SampleMemoryUsed.java:122) ~[?:?]
	at org.cyberpwn.react.controller.CommandController$1.run(CommandController.java:103) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`
**2. When i use comand /react book in console**:`null
org.bukkit.command.CommandException: Unhandled exception executing command 'react' in plugin React v4.2.3p
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.cyberpwn.react.action.ActionInstabilityCause.pollHeaftSamples(ActionInstabilityCause.java:429) ~[?:?]
	at org.cyberpwn.react.action.ActionInstabilityCause.pagePollSamples(ActionInstabilityCause.java:471) ~[?:?]
	at org.cyberpwn.react.action.ActionInstabilityCause.query(ActionInstabilityCause.java:534) ~[?:?]
	at org.cyberpwn.react.controller.CommandController$12.run(CommandController.java:759) ~[?:?]
	at org.cyberpwn.react.util.CommandRunnable.run(CommandRunnable.java:16) ~[?:?]
	at org.cyberpwn.react.util.ReactCommand.onCommand(ReactCommand.java:27) ~[?:?]
	at org.cyberpwn.react.controller.CommandController.fireCommand(CommandController.java:1249) ~[?:?]
	at org.cyberpwn.react.controller.CommandController.onCommand(CommandController.java:1409) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 13 more`
**3. I translate plugin on russian lang, but when i chose this lang - lang don't change (i also try change en file, but file overwritten after reload plugin
4. I can't connect with react program. Port is open, port is not 25565, user add**

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/React/issues/55
