### ISSUE TITLE
React 4.4.6 not working on 1.7.10

### ISSUE THREAD

**Issue by Zilacon** [cyberpwnn/React#55]
When i start up the server i get this:
```
[18:15:01 INFO]: [React] Enabling React v4.4.6p
[18:15:01 ERROR]: [React] Plugin React v4.4.6p has failed to register events for class org.cyberpwn.react.action.ActionStackEntities because org/bukkit/event/player/PlayerInteractAtEntityEvent does not exist.
[18:15:02 INFO]: [React Server]: Loading Remote Users
[18:15:02 ERROR]: Error occurred while enabling React v4.4.6p (Is it up to date?)
java.lang.NoSuchFieldError: ARMOR_STAND
	at org.cyberpwn.react.action.ActionStackEntities.onNewConfig(ActionStackEntities.java:542) ~[?:?]
	at org.cyberpwn.react.controller.DataController.load(DataController.java:139) ~[?:?]
	at org.cyberpwn.react.controller.ActionController.load(ActionController.java:72) ~[?:?]
	at org.cyberpwn.react.controller.ActionController.start(ActionController.java:81) ~[?:?]
	at org.cyberpwn.react.React.doEnable(React.java:246) ~[?:?]
	at org.cyberpwn.react.React.onEnable(React.java:140) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.56]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.56]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by cyberpwnn** [comment]
Thanks for the report. Ill fix it soon.

**Comment by Zilacon** [comment]
Holy shit that was fast! Lol.
Thank you.

**Comment by cyberpwnn** [comment]
https://www.spigotmc.org/resources/react-smart-server-performance.21057/

**Comment by Zilacon** [comment]
Still an issue on 4.5.1
```
[08:02:51 ERROR]: Error occurred while enabling React v4.5.1p (Is it up to date?)
java.lang.NoSuchFieldError: ARMOR_STAND
	at org.cyberpwn.react.action.ActionCullEntities.onNewConfig(ActionCullEntities.java:344) ~[?:?]
	at org.cyberpwn.react.controller.DataController.loadConfigurableSettings(DataController.java:204) ~[?:?]
	at org.cyberpwn.react.controller.DataController.load(DataController.java:144) ~[?:?]
	at org.cyberpwn.react.controller.ActionController.load(ActionController.java:72) ~[?:?]
	at org.cyberpwn.react.controller.ActionController.start(ActionController.java:81) ~[?:?]
	at org.cyberpwn.react.React.doEnable(React.java:248) ~[?:?]
	at org.cyberpwn.react.React.onEnable(React.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.56]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.56]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
